[package]
name = "aocf-boxes-2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
image = "0.23.14"
imageproc = "0.22.0"